alias vv="du --max-depth=1 -h | sort --human-numeric-sort"
alias psgrep="ps aux | grep -v grep | grep -i"
alias apt-update="sudo apt-get update && sudo apt-get upgrade -y"
alias now="date +%Y.%m.%d.%H.%M"
alias gpginfo="gpg --no-default-keyring --secret-keyring /dev/null -a --list-only"
alias winfo="wget -S -O /dev/null"
alias verifycrt="openssl x509 -text -noout -in"
alias verifycsr="openssl req -noout -text -verify -in"
